apiVersion: apps/v1
kind: Deployment
metadata:
  name: development-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dev-app
  template:
    metadata:
      labels:
        app: dev-app
    spec:
      containers:
      - name: dev-container
        image: us-east1-docker.pkg.dev/qwiklabs-gcp-00-d45a0b7f1f91/my-repository
        ports:
        - containerPort: 8080
